"""empty message

Revision ID: 4017d8063ef8
Revises: 6b091089b9d
Create Date: 2016-08-15 10:38:02.211653

"""

# revision identifiers, used by Alembic.
revision = '4017d8063ef8'
down_revision = '6b091089b9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
