"""empty message

Revision ID: 6b091089b9d
Revises: 3f84790e58f7
Create Date: 2016-08-13 16:24:00.026484

"""

# revision identifiers, used by Alembic.
revision = '6b091089b9d'
down_revision = '3f84790e58f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
